//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.dbfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts
    {
        public int idAccount { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public int idRole { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
