//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.dbfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        public int idTask { get; set; }
        public string nameTask { get; set; }
        public System.DateTime taskStart { get; set; }
        public System.DateTime taskFinish { get; set; }
        public int taskPeriodDays { get; set; }
        public int idProject { get; set; }
        public int idStatus { get; set; }
        public Nullable<int> idWorker { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual status status { get; set; }
        public virtual workers workers { get; set; }
    }
}
